// Extra copy for the AI-assisted Package Builder (draft banner, assistant, savings, SmartPack).

export const AI_I18N = {
  en: {
    drafting: "Aura is drafting your package…", manual: "Choose a package manually",
    draftNote: "Aura's draft — review everything and change anything you like.",
    askTitle: "Ask Aura", askPh: "e.g. make it cheaper, add a guide, we are 4 people…", ask: "Send", thinking: "Aura is thinking…",
    chips: ["Make it cheaper", "Make it more comfortable", "Explain this price"],
    proposal: (total, delta) => `Proposed new total: ${total} (${delta})`, applyChange: "Apply these changes", dismiss: "Dismiss",
    noSavings: "This is already the lowest-cost combination for this package, so there is nothing cheaper to swap in.",
    swap: (a, b) => `${a} → ${b}`, drop: (a) => `Remove: ${a}`,
    packTitle: "SmartPack checklist", packTab: "Packing", optionsTab: "Options",
  },
  zh: {
    drafting: "Aura 正在为您起草套餐…", manual: "手动选择套餐",
    draftNote: "Aura 的草稿——请检查所有内容，可随意修改。",
    askTitle: "询问 Aura", askPh: "例如：便宜一点、加一位向导、我们有 4 个人…", ask: "发送", thinking: "Aura 正在思考…",
    chips: ["便宜一点", "更舒适一些", "解释这个价格"],
    proposal: (total, delta) => `建议的新总价：${total}（${delta}）`, applyChange: "应用这些更改", dismiss: "忽略",
    noSavings: "这已是该套餐的最低价组合，没有更便宜的可替换项。",
    swap: (a, b) => `${a} → ${b}`, drop: (a) => `移除：${a}`,
    packTitle: "行李清单", packTab: "行李", optionsTab: "选项",
  },
  es: {
    drafting: "Aura está preparando tu paquete…", manual: "Elegir un paquete manualmente",
    draftNote: "Borrador de Aura: revisa todo y cambia lo que quieras.",
    askTitle: "Pregunta a Aura", askPh: "p. ej. hazlo más barato, añade un guía, somos 4…", ask: "Enviar", thinking: "Aura está pensando…",
    chips: ["Hazlo más barato", "Más comodidad", "Explica este precio"],
    proposal: (total, delta) => `Nuevo total propuesto: ${total} (${delta})`, applyChange: "Aplicar estos cambios", dismiss: "Descartar",
    noSavings: "Esta ya es la combinación más económica de este paquete; no hay nada más barato que cambiar.",
    swap: (a, b) => `${a} → ${b}`, drop: (a) => `Quitar: ${a}`,
    packTitle: "Lista de equipaje", packTab: "Equipaje", optionsTab: "Opciones",
  },
  fr: {
    drafting: "Aura prépare votre forfait…", manual: "Choisir un forfait manuellement",
    draftNote: "Brouillon d'Aura — vérifiez tout et modifiez ce que vous voulez.",
    askTitle: "Demander à Aura", askPh: "ex. moins cher, ajouter un guide, nous sommes 4…", ask: "Envoyer", thinking: "Aura réfléchit…",
    chips: ["Moins cher", "Plus de confort", "Expliquer ce prix"],
    proposal: (total, delta) => `Nouveau total proposé : ${total} (${delta})`, applyChange: "Appliquer ces changements", dismiss: "Ignorer",
    noSavings: "C'est déjà la combinaison la moins chère pour ce forfait ; rien de moins cher à substituer.",
    swap: (a, b) => `${a} → ${b}`, drop: (a) => `Retirer : ${a}`,
    packTitle: "Liste de bagages", packTab: "Valise", optionsTab: "Options",
  },
  de: {
    drafting: "Aura entwirft Ihr Paket…", manual: "Paket manuell wählen",
    draftNote: "Auras Entwurf – prüfen Sie alles und ändern Sie, was Sie möchten.",
    askTitle: "Aura fragen", askPh: "z. B. günstiger, Guide hinzufügen, wir sind 4…", ask: "Senden", thinking: "Aura denkt nach…",
    chips: ["Günstiger bitte", "Mehr Komfort", "Preis erklären"],
    proposal: (total, delta) => `Vorgeschlagene neue Summe: ${total} (${delta})`, applyChange: "Änderungen übernehmen", dismiss: "Verwerfen",
    noSavings: "Das ist bereits die günstigste Kombination für dieses Paket; es gibt nichts Günstigeres zum Tauschen.",
    swap: (a, b) => `${a} → ${b}`, drop: (a) => `Entfernen: ${a}`,
    packTitle: "Packliste", packTab: "Packen", optionsTab: "Optionen",
  },
};
