// Package Builder interface text per language. Option names come from the backend in the chosen language.

export const BUILDER_I18N = {
  en: {
    title: "Package Builder", badge: "Not booked", close: "Close builder",
    choose: "Choose a package to customise", loading: "Loading…",
    meta: (d, n) => `${d} days / ${n} nights`, back: "Back",
    travelers: "Travelers", date: "Preferred travel date", dateOpt: "(optional)",
    basis: "The package price covers your whole booking; only some options are priced per person. We arrange the hotels, meals and transport — you pay one package price, never suppliers separately.",
    perNight: "per person / night", perPerson: "per person", flat: "per booking", included: "Included", multiHint: "Choose any",
    breakdown: "Price breakdown", total: "Estimated total", review: "Review & request",
    quoteErr: "Couldn't update the price. You can keep browsing and customising manually.",
    yourDetails: "Your details", name: "Full name", email: "Email", phone: "Phone (optional)", notes: "Notes (optional)",
    confirm: "I confirm this request. I understand nothing is charged now and our team will contact me to confirm availability and payment.",
    submit: "Send booking request", submitting: "Sending…", edit: "Edit options",
    doneTitle: "Request received", doneText: (ref) => `Your reference is ${ref}. Our team will contact you to confirm availability and arrange payment. Nothing has been charged.`,
    anotherBtn: "Build another",
    errors: { bad_email: "Please enter a valid email address.", confirmation_required: "Please tick the confirmation box.", generic: "Couldn't send your request. Please try again." },
    openDraft: "Open in Package Builder",
  },
  zh: {
    title: "套餐定制", badge: "尚未预订", close: "关闭",
    choose: "选择要定制的套餐", loading: "加载中…",
    meta: (d, n) => `${d} 天 ${n} 晚`, back: "返回",
    travelers: "出行人数", date: "期望出行日期", dateOpt: "（可选）",
    basis: "套餐价格涵盖您的整个预订，仅部分选项按人数计价。酒店、餐饮和交通均由我们安排——您只需支付一个套餐价格，无需分别向供应商付款。",
    perNight: "每人/每晚", perPerson: "每人", flat: "每次预订", included: "已包含", multiHint: "可多选",
    breakdown: "价格明细", total: "预估总价", review: "确认并提交申请",
    quoteErr: "无法更新价格。您仍可继续浏览并手动定制。",
    yourDetails: "您的信息", name: "姓名", email: "电子邮箱", phone: "电话（可选）", notes: "备注（可选）",
    confirm: "我确认提交此申请。我了解目前不会收取任何费用，团队将联系我确认可订情况并安排付款。",
    submit: "提交预订申请", submitting: "提交中…", edit: "修改选项",
    doneTitle: "申请已收到", doneText: (ref) => `您的参考编号是 ${ref}。我们的团队将联系您确认可订情况并安排付款。目前未收取任何费用。`,
    anotherBtn: "再定制一个",
    errors: { bad_email: "请输入有效的电子邮箱。", confirmation_required: "请勾选确认框。", generic: "无法提交申请，请重试。" },
    openDraft: "在套餐定制中打开",
  },
  es: {
    title: "Creador de paquetes", badge: "Sin reservar", close: "Cerrar",
    choose: "Elige un paquete para personalizar", loading: "Cargando…",
    meta: (d, n) => `${d} días / ${n} noches`, back: "Volver",
    travelers: "Viajeros", date: "Fecha de viaje preferida", dateOpt: "(opcional)",
    basis: "El precio del paquete cubre toda tu reserva; solo algunas opciones se cobran por persona. Nosotros organizamos hoteles, comidas y transporte: pagas un único precio, nunca a proveedores por separado.",
    perNight: "por persona / noche", perPerson: "por persona", flat: "por reserva", included: "Incluido", multiHint: "Elige las que quieras",
    breakdown: "Desglose del precio", total: "Total estimado", review: "Revisar y solicitar",
    quoteErr: "No se pudo actualizar el precio. Puedes seguir navegando y personalizando manualmente.",
    yourDetails: "Tus datos", name: "Nombre completo", email: "Correo electrónico", phone: "Teléfono (opcional)", notes: "Notas (opcional)",
    confirm: "Confirmo esta solicitud. Entiendo que ahora no se cobra nada y que el equipo me contactará para confirmar disponibilidad y pago.",
    submit: "Enviar solicitud de reserva", submitting: "Enviando…", edit: "Editar opciones",
    doneTitle: "Solicitud recibida", doneText: (ref) => `Tu referencia es ${ref}. Nuestro equipo te contactará para confirmar disponibilidad y organizar el pago. No se ha cobrado nada.`,
    anotherBtn: "Crear otro",
    errors: { bad_email: "Introduce un correo válido.", confirmation_required: "Marca la casilla de confirmación.", generic: "No se pudo enviar la solicitud. Inténtalo de nuevo." },
    openDraft: "Abrir en el creador de paquetes",
  },
  fr: {
    title: "Créateur de forfait", badge: "Non réservé", close: "Fermer",
    choose: "Choisissez un forfait à personnaliser", loading: "Chargement…",
    meta: (d, n) => `${d} jours / ${n} nuits`, back: "Retour",
    travelers: "Voyageurs", date: "Date de voyage souhaitée", dateOpt: "(facultatif)",
    basis: "Le prix du forfait couvre toute votre réservation ; seules certaines options sont facturées par personne. Nous organisons hôtels, repas et transport : vous payez un seul prix, jamais les prestataires séparément.",
    perNight: "par personne / nuit", perPerson: "par personne", flat: "par réservation", included: "Inclus", multiHint: "Choisissez-en plusieurs",
    breakdown: "Détail du prix", total: "Total estimé", review: "Vérifier et demander",
    quoteErr: "Impossible de mettre à jour le prix. Vous pouvez continuer à parcourir et personnaliser manuellement.",
    yourDetails: "Vos coordonnées", name: "Nom complet", email: "E-mail", phone: "Téléphone (facultatif)", notes: "Remarques (facultatif)",
    confirm: "Je confirme cette demande. Je comprends que rien n'est débité maintenant et que l'équipe me contactera pour confirmer la disponibilité et le paiement.",
    submit: "Envoyer la demande de réservation", submitting: "Envoi…", edit: "Modifier les options",
    doneTitle: "Demande reçue", doneText: (ref) => `Votre référence est ${ref}. Notre équipe vous contactera pour confirmer la disponibilité et organiser le paiement. Rien n'a été débité.`,
    anotherBtn: "En créer un autre",
    errors: { bad_email: "Veuillez saisir un e-mail valide.", confirmation_required: "Veuillez cocher la case de confirmation.", generic: "Impossible d'envoyer la demande. Réessayez." },
    openDraft: "Ouvrir dans le créateur de forfait",
  },
  de: {
    title: "Paket-Konfigurator", badge: "Nicht gebucht", close: "Schließen",
    choose: "Wählen Sie ein Paket zum Anpassen", loading: "Lädt…",
    meta: (d, n) => `${d} Tage / ${n} Nächte`, back: "Zurück",
    travelers: "Reisende", date: "Gewünschtes Reisedatum", dateOpt: "(optional)",
    basis: "Der Paketpreis gilt für Ihre gesamte Buchung; nur einzelne Optionen werden pro Person berechnet. Wir organisieren Hotels, Mahlzeiten und Transport – Sie zahlen einen Paketpreis, nie einzelne Anbieter.",
    perNight: "pro Person / Nacht", perPerson: "pro Person", flat: "pro Buchung", included: "Inklusive", multiHint: "Beliebig wählbar",
    breakdown: "Preisübersicht", total: "Geschätzte Summe", review: "Prüfen & anfragen",
    quoteErr: "Preis konnte nicht aktualisiert werden. Sie können weiter stöbern und manuell anpassen.",
    yourDetails: "Ihre Angaben", name: "Vollständiger Name", email: "E-Mail", phone: "Telefon (optional)", notes: "Hinweise (optional)",
    confirm: "Ich bestätige diese Anfrage. Mir ist bewusst, dass jetzt nichts abgebucht wird und das Team mich zur Bestätigung von Verfügbarkeit und Zahlung kontaktiert.",
    submit: "Buchungsanfrage senden", submitting: "Wird gesendet…", edit: "Optionen ändern",
    doneTitle: "Anfrage erhalten", doneText: (ref) => `Ihre Referenz lautet ${ref}. Unser Team meldet sich, um Verfügbarkeit zu bestätigen und die Zahlung zu organisieren. Es wurde nichts abgebucht.`,
    anotherBtn: "Weiteres erstellen",
    errors: { bad_email: "Bitte eine gültige E-Mail-Adresse eingeben.", confirmation_required: "Bitte das Bestätigungsfeld ankreuzen.", generic: "Anfrage konnte nicht gesendet werden. Bitte erneut versuchen." },
    openDraft: "Im Paket-Konfigurator öffnen",
  },
};

BUILDER_I18N.ko = {
 title:"여행 상품 만들기", badge:"예약 전", close:"만들기 닫기", choose:"맞춤 설정할 여행 상품을 선택하세요", loading:"불러오는 중…",
 meta:(d,n)=>`${n}박 ${d}일`, back:"뒤로", travelers:"여행 인원", date:"희망 여행 날짜", dateOpt:"(선택 사항)",
 basis:"상품 가격은 전체 예약에 적용되며 일부 옵션만 1인당 계산됩니다. 숙박, 식사와 교통은 저희가 준비하며 하나의 상품 가격으로 결제합니다.",
 perNight:"1인 1박당", perPerson:"1인당", flat:"예약당", included:"포함", multiHint:"여러 항목 선택 가능",
 breakdown:"가격 내역", total:"예상 총액", review:"검토 및 요청", quoteErr:"가격을 갱신할 수 없습니다. 계속 둘러보고 직접 수정할 수 있습니다.",
 yourDetails:"예약자 정보", name:"이름", email:"이메일", phone:"전화번호 (선택 사항)", notes:"추가 요청 (선택 사항)",
 confirm:"이 요청을 제출하는 데 동의합니다. 지금은 결제되지 않으며 담당자가 예약 가능 여부와 결제 방법을 확인하기 위해 연락합니다.",
 submit:"예약 요청 보내기", submitting:"보내는 중…", edit:"옵션 수정", doneTitle:"요청이 접수되었습니다",
 doneText:ref=>`접수 번호는 ${ref}입니다. 담당자가 예약 가능 여부와 결제 방법을 안내해 드립니다. 아직 결제되지 않았습니다.`,
 anotherBtn:"다른 여행 만들기", errors:{bad_email:"올바른 이메일 주소를 입력하세요.",confirmation_required:"확인란에 동의해 주세요.",generic:"요청을 보낼 수 없습니다. 다시 시도해 주세요."},openDraft:"여행 상품 만들기에서 열기"
};