export const CURRENCY_DATA = [
  // ── Popular & Major Currencies ──
  { code: "USD", name: "US Dollar", country: "United States", keywords: "america american usa dollar", flag: "🇺🇸" },
  { code: "EUR", name: "Euro", country: "European Union (Eurozone)", keywords: "europe euro france germany italy spain netherlands belgium portugal austria ireland greece finland", flag: "🇪🇺" },
  { code: "GBP", name: "British Pound", country: "United Kingdom", keywords: "uk britain british england scotland wales london pound sterling", flag: "🇬🇧" },
  { code: "JPY", name: "Japanese Yen", country: "Japan", keywords: "japanese tokyo yen", flag: "🇯🇵" },
  { code: "CHF", name: "Swiss Franc", country: "Switzerland", keywords: "swiss franc zurich geneva", flag: "🇨🇭" },
  { code: "CAD", name: "Canadian Dollar", country: "Canada", keywords: "canadian dollar toronto", flag: "🇨🇦" },
  { code: "AUD", name: "Australian Dollar", country: "Australia", keywords: "australian sydney melbourne aussie dollar", flag: "🇦🇺" },
  { code: "NZD", name: "New Zealand Dollar", country: "New Zealand", keywords: "kiwi auckland dollar", flag: "🇳🇿" },
  { code: "CNY", name: "Chinese Yuan (RMB)", country: "China", keywords: "chinese yuan renminbi beijing", flag: "🇨🇳" },
  { code: "INR", name: "Indian Rupee", country: "India", keywords: "indian rupee inr delhi mumbai", flag: "🇮🇳" },
  { code: "LKR", name: "Sri Lankan Rupee", country: "Sri Lanka", keywords: "sri lanka colombo jaffna lkr", flag: "🇱🇰" },

  // ── South Asia ──
  { code: "AFN", name: "Afghan Afghani", country: "Afghanistan", keywords: "afghan afghani afghanistan kabul", flag: "🇦🇫" },
  { code: "PKR", name: "Pakistani Rupee", country: "Pakistan", keywords: "pakistani rupee islamabad karachi", flag: "🇵🇰" },
  { code: "BDT", name: "Bangladeshi Taka", country: "Bangladesh", keywords: "bangladesh bengali dhaka taka", flag: "🇧🇩" },
  { code: "NPR", name: "Nepalese Rupee", country: "Nepal", keywords: "nepal nepalese kathmandu rupee", flag: "🇳🇵" },
  { code: "MVR", name: "Maldivian Rufiyaa", country: "Maldives", keywords: "maldives maldivian male rufiyaa", flag: "🇲🇻" },
  { code: "BTN", name: "Bhutanese Ngultrum", country: "Bhutan", keywords: "bhutan bhutanese thimphu", flag: "🇧🇹" },

  // ── Middle East & Central Asia ──
  { code: "AED", name: "UAE Dirham", country: "United Arab Emirates", keywords: "uae dubai abu dhabi emirati dirham", flag: "🇦🇪" },
  { code: "SAR", name: "Saudi Riyal", country: "Saudi Arabia", keywords: "saudi arabia riyadh riyal", flag: "🇸🇦" },
  { code: "QAR", name: "Qatari Riyal", country: "Qatar", keywords: "qatar qatari doha riyal", flag: "🇶🇦" },
  { code: "KWD", name: "Kuwaiti Dinar", country: "Kuwait", keywords: "kuwait kuwaiti dinar", flag: "🇰🇼" },
  { code: "BHD", name: "Bahraini Dinar", country: "Bahrain", keywords: "bahrain bahraini dinar", flag: "🇧🇭" },
  { code: "OMR", name: "Omani Rial", country: "Oman", keywords: "oman omani muscat rial", flag: "🇴🇲" },
  { code: "TRY", name: "Turkish Lira", country: "Turkey", keywords: "turkey turkish istanbul lira", flag: "🇹🇷" },
  { code: "ILS", name: "Israeli New Shekel", country: "Israel", keywords: "israel israeli shekel tel aviv", flag: "🇮🇱" },
  { code: "JOD", name: "Jordanian Dinar", country: "Jordan", keywords: "jordan jordanian amman dinar", flag: "🇯🇴" },
  { code: "IQD", name: "Iraqi Dinar", country: "Iraq", keywords: "iraq iraqi baghdad dinar", flag: "🇮🇶" },
  { code: "IRR", name: "Iranian Rial", country: "Iran", keywords: "iran iranian tehran rial", flag: "🇮🇷" },
  { code: "SYP", name: "Syrian Pound", country: "Syria", keywords: "syria syrian damascus pound", flag: "🇸🇾" },
  { code: "LBP", name: "Lebanese Pound", country: "Lebanon", keywords: "lebanon lebanese beirut pound", flag: "🇱🇧" },
  { code: "YER", name: "Yemeni Rial", country: "Yemen", keywords: "yemen yemeni sanaa rial", flag: "🇾🇪" },
  { code: "KZT", name: "Kazakhstani Tenge", country: "Kazakhstan", keywords: "kazakhstan kazakh tenge almaty astana", flag: "🇰🇿" },
  { code: "UZS", name: "Uzbekistani Som", country: "Uzbekistan", keywords: "uzbekistan uzbek som tashkent", flag: "🇺🇿" },
  { code: "TMT", name: "Turkmenistani Manat", country: "Turkmenistan", keywords: "turkmenistan turkmen manat", flag: "🇹🇲" },
  { code: "KGS", name: "Kyrgyzstani Som", country: "Kyrgyzstan", keywords: "kyrgyzstan kyrgyz som bishkek", flag: "🇰🇬" },
  { code: "TJS", name: "Tajikistani Somoni", country: "Tajikistan", keywords: "tajikistan tajik somoni dushanbe", flag: "🇹🇯" },
  { code: "GEL", name: "Georgian Lari", country: "Georgia", keywords: "georgia georgian lari tbilisi", flag: "🇬🇪" },
  { code: "AMD", name: "Armenian Dram", country: "Armenia", keywords: "armenia armenian dram yerevan", flag: "🇦🇲" },
  { code: "AZN", name: "Azerbaijani Manat", country: "Azerbaijan", keywords: "azerbaijan azeri manat baku", flag: "🇦🇿" },

  // ── Southeast Asia & East Asia ──
  { code: "SGD", name: "Singapore Dollar", country: "Singapore", keywords: "singapore dollar sgd", flag: "🇸🇬" },
  { code: "MYR", name: "Malaysian Ringgit", country: "Malaysia", keywords: "malaysia malaysian ringgit kuala lumpur", flag: "🇲🇾" },
  { code: "THB", name: "Thai Baht", country: "Thailand", keywords: "thailand thai bangkok baht", flag: "🇹🇭" },
  { code: "IDR", name: "Indonesian Rupiah", country: "Indonesia", keywords: "indonesia indonesian jakarta bali rupiah", flag: "🇮🇩" },
  { code: "PHP", name: "Philippine Peso", country: "Philippines", keywords: "philippines filipino manila peso", flag: "🇵🇭" },
  { code: "VND", name: "Vietnamese Dong", country: "Vietnam", keywords: "vietnam vietnamese hanoi saigon dong", flag: "🇻🇳" },
  { code: "MMK", name: "Myanmar Kyat", country: "Myanmar (Burma)", keywords: "myanmar burma burmese yangon kyat", flag: "🇲🇲" },
  { code: "KHR", name: "Cambodian Riel", country: "Cambodia", keywords: "cambodia cambodian phnom penh riel", flag: "🇰🇭" },
  { code: "LAK", name: "Lao Kip", country: "Laos", keywords: "laos laotian vientiane kip", flag: "🇱🇦" },
  { code: "BND", name: "Brunei Dollar", country: "Brunei", keywords: "brunei dollar", flag: "🇧🇳" },
  { code: "HKD", name: "Hong Kong Dollar", country: "Hong Kong", keywords: "hong kong hk dollar", flag: "🇭🇰" },
  { code: "TWD", name: "New Taiwan Dollar", country: "Taiwan", keywords: "taiwan taiwanese taipei dollar", flag: "🇹🇼" },
  { code: "KRW", name: "South Korean Won", country: "South Korea", keywords: "korea korean seoul won", flag: "🇰🇷" },
  { code: "KPW", name: "North Korean Won", country: "North Korea", keywords: "north korea pyongyang won", flag: "🇰🇵" },
  { code: "MNT", name: "Mongolian Tugrik", country: "Mongolia", keywords: "mongolia mongolian tugrik", flag: "🇲🇳" },
  { code: "MOP", name: "Macanese Pataca", country: "Macau", keywords: "macau macanese pataca", flag: "🇲🇴" },

  // ── Europe (Individual Nations) ──
  { code: "EUR", name: "Euro", country: "France", keywords: "france french paris euro", flag: "🇫🇷" },
  { code: "EUR", name: "Euro", country: "Germany", keywords: "germany german deutschland berlin euro", flag: "🇩🇪" },
  { code: "EUR", name: "Euro", country: "Italy", keywords: "italy italian italia rome euro", flag: "🇮🇹" },
  { code: "EUR", name: "Euro", country: "Spain", keywords: "spain spanish espana madrid euro", flag: "🇪🇸" },
  { code: "EUR", name: "Euro", country: "Netherlands", keywords: "netherlands dutch holland amsterdam euro", flag: "🇳🇱" },
  { code: "EUR", name: "Euro", country: "Belgium", keywords: "belgium belgian brussels euro", flag: "🇧🇪" },
  { code: "EUR", name: "Euro", country: "Austria", keywords: "austria austrian vienna euro", flag: "🇦🇹" },
  { code: "EUR", name: "Euro", country: "Portugal", keywords: "portugal portuguese lisbon euro", flag: "🇵🇹" },
  { code: "EUR", name: "Euro", country: "Ireland", keywords: "ireland irish dublin euro", flag: "🇮🇪" },
  { code: "EUR", name: "Euro", country: "Greece", keywords: "greece greek athens euro", flag: "🇬🇷" },
  { code: "EUR", name: "Euro", country: "Finland", keywords: "finland finnish helsinki euro", flag: "🇫🇮" },
  { code: "SEK", name: "Swedish Krona", country: "Sweden", keywords: "sweden swedish stockholm krona", flag: "🇸🇪" },
  { code: "NOK", name: "Norwegian Krone", country: "Norway", keywords: "norway norwegian oslo krone", flag: "🇳🇴" },
  { code: "DKK", name: "Danish Krone", country: "Denmark", keywords: "denmark danish copenhagen krone", flag: "🇩🇰" },
  { code: "ISK", name: "Icelandic Krona", country: "Iceland", keywords: "iceland icelandic reykjavik krona", flag: "🇮🇸" },
  { code: "PLN", name: "Polish Zloty", country: "Poland", keywords: "poland polish warsaw zloty", flag: "🇵🇱" },
  { code: "CZK", name: "Czech Koruna", country: "Czech Republic", keywords: "czech czechia prague koruna", flag: "🇨🇿" },
  { code: "HUF", name: "Hungarian Forint", country: "Hungary", keywords: "hungary hungarian budapest forint", flag: "🇭🇺" },
  { code: "RON", name: "Romanian Leu", country: "Romania", keywords: "romania romanian bucharest leu", flag: "🇷🇴" },
  { code: "BGN", name: "Bulgarian Lev", country: "Bulgaria", keywords: "bulgaria bulgarian sofia lev", flag: "🇧🇬" },
  { code: "RSD", name: "Serbian Dinar", country: "Serbia", keywords: "serbia serbian belgrade dinar", flag: "🇷🇸" },
  { code: "BAM", name: "Bosnian Mark", country: "Bosnia & Herzegovina", keywords: "bosnia herzegovina sarajevo mark", flag: "🇧🇦" },
  { code: "MKD", name: "Macedonian Denar", country: "North Macedonia", keywords: "macedonia macedonian skopje denar", flag: "🇲🇰" },
  { code: "ALL", name: "Albanian Lek", country: "Albania", keywords: "albania albanian tirana lek", flag: "🇦🇱" },
  { code: "MDL", name: "Moldovan Leu", country: "Moldova", keywords: "moldova moldovan leu", flag: "🇲🇩" },
  { code: "UAH", name: "Ukrainian Hryvnia", country: "Ukraine", keywords: "ukraine ukrainian kyiv hryvnia", flag: "🇺🇦" },
  { code: "BYN", name: "Belarusian Ruble", country: "Belarus", keywords: "belarus belarusian minsk ruble", flag: "🇧🇾" },
  { code: "RUB", name: "Russian Ruble", country: "Russia", keywords: "russia russian moscow ruble", flag: "🇷🇺" },

  // ── Americas ──
  { code: "MXN", name: "Mexican Peso", country: "Mexico", keywords: "mexico mexican peso", flag: "🇲🇽" },
  { code: "BRL", name: "Brazilian Real", country: "Brazil", keywords: "brazil brazilian real sao paulo rio", flag: "🇧🇷" },
  { code: "ARS", name: "Argentine Peso", country: "Argentina", keywords: "argentina argentine buenos aires peso", flag: "🇦🇷" },
  { code: "CLP", name: "Chilean Peso", country: "Chile", keywords: "chile chilean santiago peso", flag: "🇨🇱" },
  { code: "COP", name: "Colombian Peso", country: "Colombia", keywords: "colombia colombian bogota peso", flag: "🇨🇴" },
  { code: "PEN", name: "Peruvian Sol", country: "Peru", keywords: "peru peruvian lima sol", flag: "🇵🇪" },
  { code: "UYU", name: "Uruguayan Peso", country: "Uruguay", keywords: "uruguay uruguayan montevideo peso", flag: "🇺🇾" },
  { code: "PYG", name: "Paraguayan Guarani", country: "Paraguay", keywords: "paraguay paraguayan guarani", flag: "🇵🇾" },
  { code: "BOB", name: "Bolivian Boliviano", country: "Bolivia", keywords: "bolivia bolivian la paz boliviano", flag: "🇧🇴" },
  { code: "VES", name: "Venezuelan Bolívar", country: "Venezuela", keywords: "venezuela venezuelan caracas bolivar", flag: "🇻🇪" },
  { code: "GYD", name: "Guyanese Dollar", country: "Guyana", keywords: "guyana guyanese dollar", flag: "🇬🇾" },
  { code: "SRD", name: "Surinamese Dollar", country: "Suriname", keywords: "suriname surinamese dollar", flag: "🇸🇷" },
  { code: "CRC", name: "Costa Rican Colón", country: "Costa Rica", keywords: "costa rica costarican colon", flag: "🇨🇷" },
  { code: "PAB", name: "Panamanian Balboa", country: "Panama", keywords: "panama panamanian balboa", flag: "🇵🇦" },
  { code: "GTQ", name: "Guatemalan Quetzal", country: "Guatemala", keywords: "guatemala guatemalan quetzal", flag: "🇬🇹" },
  { code: "HNL", name: "Honduran Lempira", country: "Honduras", keywords: "honduras honduran lempira", flag: "🇭🇳" },
  { code: "NIO", name: "Nicaraguan Córdoba", country: "Nicaragua", keywords: "nicaragua nicaraguan cordoba", flag: "🇳🇮" },
  { code: "DOP", name: "Dominican Peso", country: "Dominican Republic", keywords: "dominican republic santo domingo peso", flag: "🇩🇴" },
  { code: "CUP", name: "Cuban Peso", country: "Cuba", keywords: "cuba cuban havana peso", flag: "🇨🇺" },
  { code: "HTG", name: "Haitian Gourde", country: "Haiti", keywords: "haiti haitian gourde", flag: "🇭🇹" },
  { code: "JMD", name: "Jamaican Dollar", country: "Jamaica", keywords: "jamaica jamaican kingston dollar", flag: "🇯🇲" },
  { code: "TTD", name: "Trinidad & Tobago Dollar", country: "Trinidad and Tobago", keywords: "trinidad tobago dollar", flag: "🇹🇹" },
  { code: "BBD", name: "Barbadian Dollar", country: "Barbados", keywords: "barbados bajan dollar", flag: "🇧🇧" },
  { code: "BSD", name: "Bahamian Dollar", country: "Bahamas", keywords: "bahamas bahamian dollar", flag: "🇧🇸" },
  { code: "BZD", name: "Belize Dollar", country: "Belize", keywords: "belize belizean dollar", flag: "🇧🇿" },
  { code: "XCD", name: "East Caribbean Dollar", country: "Eastern Caribbean", keywords: "antigua barbuda dominica grenada saint lucia st kitts", flag: "🏝️" },

  // ── Africa ──
  { code: "ZAR", name: "South African Rand", country: "South Africa", keywords: "south africa south african rand cape town", flag: "🇿🇦" },
  { code: "NGN", name: "Nigerian Naira", country: "Nigeria", keywords: "nigeria nigerian lagos abuja naira", flag: "🇳🇬" },
  { code: "KES", name: "Kenyan Shilling", country: "Kenya", keywords: "kenya kenyan nairobi shilling", flag: "🇰🇪" },
  { code: "EGP", name: "Egyptian Pound", country: "Egypt", keywords: "egypt egyptian cairo pound", flag: "🇪🇬" },
  { code: "GHS", name: "Ghanaian Cedi", country: "Ghana", keywords: "ghana ghanaian accra cedi", flag: "🇬🇭" },
  { code: "TZS", name: "Tanzanian Shilling", country: "Tanzania", keywords: "tanzania tanzanian shilling", flag: "🇹🇿" },
  { code: "UGX", name: "Ugandan Shilling", country: "Uganda", keywords: "uganda ugandan kampala shilling", flag: "🇺🇬" },
  { code: "ETB", name: "Ethiopian Birr", country: "Ethiopia", keywords: "ethiopia ethiopian addis ababa birr", flag: "🇪🇹" },
  { code: "MAD", name: "Moroccan Dirham", country: "Morocco", keywords: "morocco moroccan marrakech dirham", flag: "🇲🇦" },
  { code: "DZD", name: "Algerian Dinar", country: "Algeria", keywords: "algeria algerian dinar", flag: "🇩🇿" },
  { code: "TND", name: "Tunisian Dinar", country: "Tunisia", keywords: "tunisia tunisian dinar", flag: "🇹🇳" },
  { code: "LYD", name: "Libyan Dinar", country: "Libya", keywords: "libya libyan dinar", flag: "🇱🇾" },
  { code: "SDG", name: "Sudanese Pound", country: "Sudan", keywords: "sudan sudanese pound", flag: "🇸🇩" },
  { code: "SSP", name: "South Sudanese Pound", country: "South Sudan", keywords: "south sudan pound", flag: "🇸🇸" },
  { code: "SOS", name: "Somali Shilling", country: "Somalia", keywords: "somalia somali mogadishu shilling", flag: "🇸🇴" },
  { code: "DJF", name: "Djiboutian Franc", country: "Djibouti", keywords: "djibouti franc", flag: "🇩🇯" },
  { code: "ERN", name: "Eritrean Nakfa", country: "Eritrea", keywords: "eritrea eritrean nakfa", flag: "🇪🇷" },
  { code: "RWF", name: "Rwandan Franc", country: "Rwanda", keywords: "rwanda rwandan kigali franc", flag: "🇷🇼" },
  { code: "BIF", name: "Burundian Franc", country: "Burundi", keywords: "burundi burundian franc", flag: "🇧🇮" },
  { code: "CDF", name: "Congolese Franc", country: "DR Congo", keywords: "congo kinshasa franc", flag: "🇨🇩" },
  { code: "XAF", name: "Central African CFA Franc", country: "Central Africa (Cameroon/Gabon)", keywords: "cameroon gabon congo chad cfa franc", flag: "🌍" },
  { code: "XOF", name: "West African CFA Franc", country: "West Africa (Senegal/Ivory Coast)", keywords: "senegal ivory coast dakar abidjan cfa franc", flag: "🌍" },
  { code: "AOA", name: "Angolan Kwanza", country: "Angola", keywords: "angola angolan kwanza", flag: "🇦🇴" },
  { code: "MZN", name: "Mozambican Metical", country: "Mozambique", keywords: "mozambique mozambican metical", flag: "🇲🇿" },
  { code: "ZMW", name: "Zambian Kwacha", country: "Zambia", keywords: "zambia zambian kwacha", flag: "🇿🇲" },
  { code: "MWK", name: "Malawian Kwacha", country: "Malawi", keywords: "malawi malawian kwacha", flag: "🇲🇼" },
  { code: "BWP", name: "Botswana Pula", country: "Botswana", keywords: "botswana pula", flag: "🇧🇼" },
  { code: "NAD", name: "Namibian Dollar", country: "Namibia", keywords: "namibia namibian dollar", flag: "🇳🇦" },
  { code: "SZL", name: "Eswatini Lilangeni", country: "Eswatini", keywords: "eswatini swaziland lilangeni", flag: "🇸🇿" },
  { code: "LSL", name: "Lesotho Loti", country: "Lesotho", keywords: "lesotho loti", flag: "🇱🇸" },
  { code: "ZWL", name: "Zimbabwean Dollar", country: "Zimbabwe", keywords: "zimbabwe zimbabwean dollar", flag: "🇿🇼" },
  { code: "MGA", name: "Malagasy Ariary", country: "Madagascar", keywords: "madagascar malagasy ariary", flag: "🇲🇬" },
  { code: "MUR", name: "Mauritian Rupee", country: "Mauritius", keywords: "mauritius mauritian rupee", flag: "🇲🇺" },
  { code: "SCR", name: "Seychellois Rupee", country: "Seychelles", keywords: "seychelles rupee", flag: "🇸🇨" },
  { code: "GMD", name: "Gambian Dalasi", country: "Gambia", keywords: "gambia gambian dalasi", flag: "🇬🇲" },
  { code: "SLL", name: "Sierra Leonean Leone", country: "Sierra Leone", keywords: "sierra leone leone", flag: "🇸🇱" },
  { code: "LRD", name: "Liberian Dollar", country: "Liberia", keywords: "liberia liberian dollar", flag: "🇱🇷" },
  { code: "GNF", name: "Guinean Franc", country: "Guinea", keywords: "guinea guinean franc", flag: "🇬🇳" },
  { code: "MRU", name: "Mauritanian Ouguiya", country: "Mauritania", keywords: "mauritania ouguiya", flag: "🇲🇷" },

  // ── Pacific & Oceania ──
  { code: "FJD", name: "Fijian Dollar", country: "Fiji", keywords: "fiji fijian dollar", flag: "🇫🇯" },
  { code: "PGK", name: "Papua New Guinean Kina", country: "Papua New Guinea", keywords: "papua new guinea kina", flag: "🇵🇬" },
  { code: "WST", name: "Samoan Tala", country: "Samoa", keywords: "samoa samoan tala", flag: "🇼🇸" },
  { code: "TOP", name: "Tongan Paʻanga", country: "Tonga", keywords: "tonga tongan paanga", flag: "🇹🇴" },
  { code: "VUV", name: "Vanuatu Vatu", country: "Vanuatu", keywords: "vanuatu vatu", flag: "🇻🇺" },
  { code: "SBD", name: "Solomon Islands Dollar", country: "Solomon Islands", keywords: "solomon islands dollar", flag: "🇸🇧" },
  { code: "XPF", name: "CFP Franc", country: "French Polynesia / New Caledonia", keywords: "tahiti polynesie caledonie cfp", flag: "🇵🇫" },
];
