// Draft panel copy per language. Functions take the values to interpolate.
// Dynamic content (titles, activities, checklist items) comes from the backend in the chosen language.

export const DRAFT_I18N = {
  en: {
    badge: "Draft · not booked", building: "Building your draft…", generating: "Generating your itinerary…",
    progress: (s) => `Checking our verified catalogue · ${s}s of up to 15s. You can close this and keep browsing.`,
    tryAgain: "Try again",
    timeout: "This is taking longer than expected. Nothing was booked — you can try again, or keep browsing and customizing manually.",
    aiDown: "AI suggestions are temporarily unavailable. You can continue browsing, customizing, and booking manually.",
    noMatch: "I couldn't match that to our verified catalogue. Try describing your interests, trip length or budget.",
    couldnt: "Couldn't fulfil:",
    dropped: (l) => `Some suggested days were not found in the catalogue and were removed: ${l}.`,
    tabs: ["Itinerary", "Budget", "SmartPack"],
    dayN: (n) => `Day ${n}`, from: "From", up: "Move up", down: "Move down", removeDay: "Remove day",
    allRemoved: "All days removed. Close this and ask Aura for a new draft.",
    budgetLabel: "Target budget (LKR)", budgetPh: "e.g. 250000",
    within: (c, b) => `You're within budget ✓ (${c} of ${b}).`,
    over: (c, b, o) => `Current ${c} · budget ${b} · over by ${o}`,
    noSwap: "No cheaper verified swap exists for this itinerary. You could remove a day instead.",
    save: (s) => `Save ${s}`, newTotal: (t) => `new total ${t}`, meets: "meets budget",
    instead: "Instead:", tradeoff: (a, b) => `Trade-off: you'd do “${b}” instead of “${a}”.`,
    accept: "Accept this swap",
    enterBudget: "Enter a budget to see where savings are possible. Nothing changes unless you accept a swap.",
    monthLabel: "Travel month (optional)", monthPh: "e.g. January",
    create: "Create my checklist", creating: "Creating…",
    packHint: "Based on your itinerary and Sri Lanka's general climate. Live weather isn't available here, so check a forecast before you travel.",
    packed: (d, n) => `${d}/${n} packed`, addPh: "Add your own item…", add: "Add", mine: "My items", remove: "Remove",
    total: "Indicative total",
    note: "Indicative: official package prices, pro-rata for custom day mixes. Availability for your dates is not verified; final price is confirmed with us. Nothing is booked or charged until you confirm.",
    close: "Close draft",
  },
  zh: {
    badge: "草稿 · 尚未预订", building: "正在生成草稿…", generating: "正在生成您的行程…",
    progress: (s) => `正在查询我们已核实的目录 · 已用 ${s} 秒（最长 15 秒）。您可以关闭此窗口继续浏览。`,
    tryAgain: "重试",
    timeout: "耗时比预期更长。未进行任何预订——您可以重试，或继续手动浏览和定制。",
    aiDown: "AI 建议暂时不可用。您仍可继续浏览、定制和手动预订。",
    noMatch: "未能匹配到我们已核实的目录。请描述您的兴趣、行程天数或预算。",
    couldnt: "无法满足：",
    dropped: (l) => `部分建议的天数在目录中找不到，已被移除：${l}。`,
    tabs: ["行程", "预算", "行李清单"],
    dayN: (n) => `第 ${n} 天`, from: "来自", up: "上移", down: "下移", removeDay: "删除此天",
    allRemoved: "所有天数已删除。请关闭并让 Aura 重新生成草稿。",
    budgetLabel: "目标预算 (LKR)", budgetPh: "例如 250000",
    within: (c, b) => `在预算内 ✓（${c} / ${b}）。`,
    over: (c, b, o) => `当前 ${c} · 预算 ${b} · 超出 ${o}`,
    noSwap: "此行程没有更便宜的已核实替换方案。您可以考虑删除一天。",
    save: (s) => `节省 ${s}`, newTotal: (t) => `新总价 ${t}`, meets: "符合预算",
    instead: "改为：", tradeoff: (a, b) => `取舍：您将体验“${b}”，而不是“${a}”。`,
    accept: "接受此替换",
    enterBudget: "输入预算以查看可节省之处。除非您接受替换，否则不会有任何更改。",
    monthLabel: "出行月份（可选）", monthPh: "例如 一月",
    create: "生成我的清单", creating: "生成中…",
    packHint: "基于您的行程和斯里兰卡的一般气候。此处无法获取实时天气，出发前请查看天气预报。",
    packed: (d, n) => `已打包 ${d}/${n}`, addPh: "添加您自己的物品…", add: "添加", mine: "我的物品", remove: "删除",
    total: "参考总价",
    note: "仅供参考：按官方套餐价格计算，自定义组合按天数比例估算。未核实您所选日期的可订情况；最终价格以我们确认为准。在您确认之前不会预订或扣款。",
    close: "关闭草稿",
  },
  es: {
    badge: "Borrador · sin reservar", building: "Creando tu borrador…", generating: "Generando tu itinerario…",
    progress: (s) => `Consultando nuestro catálogo verificado · ${s}s de hasta 15s. Puedes cerrar esto y seguir navegando.`,
    tryAgain: "Reintentar",
    timeout: "Está tardando más de lo esperado. No se reservó nada: puedes reintentar o seguir navegando y personalizando manualmente.",
    aiDown: "Las sugerencias de IA no están disponibles temporalmente. Puedes seguir navegando, personalizando y reservando manualmente.",
    noMatch: "No pude relacionarlo con nuestro catálogo verificado. Describe tus intereses, duración o presupuesto.",
    couldnt: "No se pudo cumplir:",
    dropped: (l) => `Algunos días sugeridos no estaban en el catálogo y se eliminaron: ${l}.`,
    tabs: ["Itinerario", "Presupuesto", "Equipaje"],
    dayN: (n) => `Día ${n}`, from: "De", up: "Subir", down: "Bajar", removeDay: "Quitar día",
    allRemoved: "Se quitaron todos los días. Cierra y pide a Aura un nuevo borrador.",
    budgetLabel: "Presupuesto objetivo (LKR)", budgetPh: "p. ej. 250000",
    within: (c, b) => `Estás dentro del presupuesto ✓ (${c} de ${b}).`,
    over: (c, b, o) => `Actual ${c} · presupuesto ${b} · excedido por ${o}`,
    noSwap: "No hay un cambio verificado más barato para este itinerario. Puedes quitar un día.",
    save: (s) => `Ahorra ${s}`, newTotal: (t) => `nuevo total ${t}`, meets: "cumple el presupuesto",
    instead: "En su lugar:", tradeoff: (a, b) => `Compromiso: harías “${b}” en lugar de “${a}”.`,
    accept: "Aceptar este cambio",
    enterBudget: "Introduce un presupuesto para ver dónde ahorrar. Nada cambia si no aceptas un cambio.",
    monthLabel: "Mes de viaje (opcional)", monthPh: "p. ej. enero",
    create: "Crear mi lista", creating: "Creando…",
    packHint: "Basada en tu itinerario y el clima general de Sri Lanka. No hay clima en vivo aquí; consulta el pronóstico antes de viajar.",
    packed: (d, n) => `${d}/${n} listo`, addPh: "Añade tu propio artículo…", add: "Añadir", mine: "Mis artículos", remove: "Quitar",
    total: "Total orientativo",
    note: "Orientativo: precios oficiales de paquete, proporcionales para combinaciones personalizadas. La disponibilidad en tus fechas no está verificada; el precio final lo confirmamos nosotros. No se reserva ni cobra nada hasta que confirmes.",
    close: "Cerrar borrador",
  },
  fr: {
    badge: "Brouillon · non réservé", building: "Création de votre brouillon…", generating: "Génération de votre itinéraire…",
    progress: (s) => `Consultation de notre catalogue vérifié · ${s}s sur 15s max. Vous pouvez fermer et continuer à naviguer.`,
    tryAgain: "Réessayer",
    timeout: "Cela prend plus de temps que prévu. Rien n'a été réservé — réessayez ou continuez à naviguer et personnaliser manuellement.",
    aiDown: "Les suggestions IA sont temporairement indisponibles. Vous pouvez continuer à parcourir, personnaliser et réserver manuellement.",
    noMatch: "Je n'ai pas pu relier cela à notre catalogue vérifié. Décrivez vos centres d'intérêt, la durée ou le budget.",
    couldnt: "Non réalisable :",
    dropped: (l) => `Certains jours suggérés n'existent pas dans le catalogue et ont été retirés : ${l}.`,
    tabs: ["Itinéraire", "Budget", "Valise"],
    dayN: (n) => `Jour ${n}`, from: "Depuis", up: "Monter", down: "Descendre", removeDay: "Supprimer le jour",
    allRemoved: "Tous les jours ont été supprimés. Fermez et demandez un nouveau brouillon à Aura.",
    budgetLabel: "Budget cible (LKR)", budgetPh: "ex. 250000",
    within: (c, b) => `Vous êtes dans le budget ✓ (${c} sur ${b}).`,
    over: (c, b, o) => `Actuel ${c} · budget ${b} · dépassement de ${o}`,
    noSwap: "Aucune alternative vérifiée moins chère pour cet itinéraire. Vous pouvez retirer un jour.",
    save: (s) => `Économisez ${s}`, newTotal: (t) => `nouveau total ${t}`, meets: "respecte le budget",
    instead: "À la place :", tradeoff: (a, b) => `Compromis : vous feriez « ${b} » au lieu de « ${a} ».`,
    accept: "Accepter ce changement",
    enterBudget: "Saisissez un budget pour voir où économiser. Rien ne change sans votre accord.",
    monthLabel: "Mois du voyage (facultatif)", monthPh: "ex. janvier",
    create: "Créer ma liste", creating: "Création…",
    packHint: "Basée sur votre itinéraire et le climat général du Sri Lanka. La météo en direct n'est pas disponible ; consultez les prévisions avant le départ.",
    packed: (d, n) => `${d}/${n} prêts`, addPh: "Ajoutez votre propre article…", add: "Ajouter", mine: "Mes articles", remove: "Retirer",
    total: "Total indicatif",
    note: "Indicatif : prix officiels des forfaits, au prorata pour les combinaisons personnalisées. La disponibilité à vos dates n'est pas vérifiée ; le prix final est confirmé par nos soins. Rien n'est réservé ni débité avant votre confirmation.",
    close: "Fermer le brouillon",
  },
  de: {
    badge: "Entwurf · nicht gebucht", building: "Entwurf wird erstellt…", generating: "Ihr Reiseplan wird erstellt…",
    progress: (s) => `Unser geprüfter Katalog wird abgefragt · ${s}s von max. 15s. Sie können dies schließen und weiterstöbern.`,
    tryAgain: "Erneut versuchen",
    timeout: "Das dauert länger als erwartet. Es wurde nichts gebucht – versuchen Sie es erneut oder stöbern und passen Sie manuell an.",
    aiDown: "KI-Vorschläge sind vorübergehend nicht verfügbar. Sie können weiter stöbern, anpassen und manuell buchen.",
    noMatch: "Das ließ sich nicht mit unserem geprüften Katalog abgleichen. Beschreiben Sie Interessen, Dauer oder Budget.",
    couldnt: "Nicht erfüllbar:",
    dropped: (l) => `Einige vorgeschlagene Tage fehlen im Katalog und wurden entfernt: ${l}.`,
    tabs: ["Reiseplan", "Budget", "Packliste"],
    dayN: (n) => `Tag ${n}`, from: "Aus", up: "Nach oben", down: "Nach unten", removeDay: "Tag entfernen",
    allRemoved: "Alle Tage entfernt. Schließen Sie dies und bitten Sie Aura um einen neuen Entwurf.",
    budgetLabel: "Zielbudget (LKR)", budgetPh: "z. B. 250000",
    within: (c, b) => `Sie liegen im Budget ✓ (${c} von ${b}).`,
    over: (c, b, o) => `Aktuell ${c} · Budget ${b} · Überschreitung ${o}`,
    noSwap: "Für diesen Reiseplan gibt es keinen günstigeren geprüften Tausch. Sie könnten einen Tag entfernen.",
    save: (s) => `Sparen Sie ${s}`, newTotal: (t) => `neue Summe ${t}`, meets: "im Budget",
    instead: "Stattdessen:", tradeoff: (a, b) => `Kompromiss: Sie erleben „${b}“ statt „${a}“.`,
    accept: "Diesen Tausch annehmen",
    enterBudget: "Geben Sie ein Budget ein, um Sparmöglichkeiten zu sehen. Ohne Ihre Zustimmung ändert sich nichts.",
    monthLabel: "Reisemonat (optional)", monthPh: "z. B. Januar",
    create: "Meine Liste erstellen", creating: "Wird erstellt…",
    packHint: "Basiert auf Ihrem Reiseplan und dem allgemeinen Klima Sri Lankas. Live-Wetter ist hier nicht verfügbar; prüfen Sie vor der Reise die Vorhersage.",
    packed: (d, n) => `${d}/${n} gepackt`, addPh: "Eigenen Punkt hinzufügen…", add: "Hinzufügen", mine: "Meine Punkte", remove: "Entfernen",
    total: "Richtsumme",
    note: "Richtwert: offizielle Paketpreise, bei individuellen Tagesmischungen anteilig. Die Verfügbarkeit für Ihre Termine ist nicht geprüft; den Endpreis bestätigen wir. Es wird nichts gebucht oder abgebucht, bevor Sie bestätigen.",
    close: "Entwurf schließen",
  },
};

