import { plannerText } from "./plannerI18n.js";
export default function TripPreparation({ value, onChange, lang = "en" }) {
  const update = (key, next) => onChange({ ...value, [key]: next });
  return <fieldset className="trip-preparation"><legend>{plannerText(lang, "Food & stay preparation")}</legend><p>{plannerText(lang, "Does anyone traveling have allergies or need preparations before arrival?")}</p>
    <label>{plannerText(lang, "What type of food do you prefer?")}<select className="bp-input" required value={value.diet || ""} onChange={e => update("diet", e.target.value)}><option value="">{plannerText(lang, "Choose your food preference")}</option><option value="vegetarian">{plannerText(lang, "Vegetarian")}</option><option value="non_vegetarian">{plannerText(lang, "Non-vegetarian")}</option><option value="vegan">{plannerText(lang, "Vegan")}</option><option value="other">{plannerText(lang, "Other — discuss with the team")}</option><option value="no_preference">{plannerText(lang, "No preference")}</option></select></label>
    <label>{plannerText(lang, "Food allergies or dietary needs")}<select className="bp-input" required value={value.food_status} onChange={e => update("food_status", e.target.value)}><option value="">{plannerText(lang, "Choose an answer")}</option><option value="none">{plannerText(lang, "None")}</option><option value="needs">{plannerText(lang, "Yes — add details")}</option><option value="private">{plannerText(lang, "Discuss privately with the team")}</option></select></label>
    {value.food_status === "needs" && <label>{plannerText(lang, "What should the food team prepare for?")}<textarea className="bp-input" required maxLength={500} placeholder={plannerText(lang, "Allergens, cross-contact concerns, or dietary preferences")} value={value.food_details} onChange={e => update("food_details", e.target.value)} /></label>}
    <label>{plannerText(lang, "Stay, accessibility or emergency preparations")}<select className="bp-input" required value={value.stay_status} onChange={e => update("stay_status", e.target.value)}><option value="">{plannerText(lang, "Choose an answer")}</option><option value="none">{plannerText(lang, "None")}</option><option value="needs">{plannerText(lang, "Yes — add details")}</option><option value="private">{plannerText(lang, "Discuss privately with the team")}</option></select></label>
    {value.stay_status === "needs" && <label>{plannerText(lang, "What should the stay team arrange before arrival?")}<textarea className="bp-input" required maxLength={500} placeholder={plannerText(lang, "Step-free access, medication storage, or an agreed emergency arrangement")} value={value.stay_details} onChange={e => update("stay_details", e.target.value)} /></label>}
    <small>{plannerText(lang, "Share only what the team needs to prepare. Arrangements must be confirmed with the food and stay providers before travel.")}</small>
  </fieldset>;
}
export const emptyPreparation = { diet: "", food_status: "", food_details: "", stay_status: "", stay_details: "" };
